services:
  - type: web
    name: dashboard-ventas
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USERS
        sync: false
      - key: ODOO_URL
        sync: false
      - key: ODOO_DB
        sync: false
      - key: ODOO_USERNAME
        sync: false
      - key: ODOO_PASSWORD
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
